-- ============================================================
-- Millwork.io SAMPLE DATA — 20 records per major table
-- Run AFTER schema.sql and seed.sql. Safe to re-run (idempotent).
-- All author_id / seller_id / claimed_by left NULL (profiles FK
-- to auth.users, so real users must post/own content).
-- ============================================================

-- ------------------------------------------------------------
-- SUPPLIERS (extends the 4 in seed.sql to 20)
-- ------------------------------------------------------------
insert into public.suppliers (name, slug, category, trade, logo_initials, description, website, phone, email, address, rating, review_count, badges, is_verified, is_approved) values
  ('Häfele America', 'hafele-america', 'Cabinet Hardware', 'hardware-accessories', 'Hä', 'Full-line hardware supplier — hinges, runners, lighting, functional fittings for commercial and residential millwork.', 'https://www.hafele.com/us', '800-423-3531', 'info@hafele.us', '3901 Cheyenne Dr, Archdale, NC 27263', 4.7, 612, '{"✓ Verified","Distributor"}'::text[], true, true),
  ('Richelieu Hardware', 'richelieu-hardware', 'Cabinet Hardware', 'hardware-accessories', 'Ri', 'North American distributor of decorative and functional hardware — pulls, knobs, pull-outs, closet systems.', 'https://www.richelieu.com', '800-361-6000', 'sales@richelieu.com', '7900 W Henri-Bourassa, Montreal, QC', 4.6, 548, '{"✓ Verified","Distributor"}'::text[], true, true),
  ('Rev-A-Shelf', 'rev-a-shelf', 'Storage Solutions', 'hardware-accessories', 'RA', 'Innovative storage and organization products — lazy susans, pull-outs, waste containers, drawer organizers.', 'https://www.rev-a-shelf.com', '800-626-1126', 'info@rev-a-shelf.com', '2409 Plantside Dr, Jeffersontown, KY 40299', 4.7, 489, '{"✓ Verified","Manufacturer"}'::text[], true, true),
  ('Biesse America', 'biesse-america', 'CNC Machinery', 'cnc-machining', 'Bi', 'Italian CNC routers, edge banders, and panel processing centers. Major installer base across North American custom shops.', 'https://www.biesseamerica.com', '704-357-3131', 'info@biesseamerica.com', '4110 Meadow Oak Dr, Charlotte, NC 28208', 4.8, 312, '{"⭐ Gold Sponsor","✓ Verified","Manufacturer"}'::text[], true, true),
  ('SCM Group USA', 'scm-group-usa', 'CNC Machinery', 'cnc-machining', 'SC', 'Woodworking machinery — CNC, edge banders, panel saws, sanders. The other half of the Italian duopoly.', 'https://www.scmgroup.com/en_US', '770-813-8818', 'scmusa@scmgroup.com', '2475 Satellite Blvd, Duluth, GA 30096', 4.7, 287, '{"✓ Verified","Manufacturer"}'::text[], true, true),
  ('Thermwood Corp', 'thermwood-corp', 'CNC Machinery', 'cnc-machining', 'Th', 'U.S. manufacturer of 3-axis and 5-axis CNC routers. Known for LSAM large-scale additive manufacturing systems.', 'https://www.thermwood.com', '800-476-8665', 'info@thermwood.com', '904 Buffaloville Rd, Dale, IN 47523', 4.6, 198, '{"✓ Verified","Manufacturer"}'::text[], true, true),
  ('Felder Group USA', 'felder-group-usa', 'Shop Machinery', 'cnc-machining', 'Fe', 'Austrian precision machinery — sliding table saws, jointers, planers, shapers, CNCs for serious shops.', 'https://www.felder-group.com/en-us', '866-792-5288', 'info@felderusa.com', '2 Lukens Dr, New Castle, DE 19720', 4.8, 245, '{"✓ Verified","Manufacturer"}'::text[], true, true),
  ('Stiles Machinery', 'stiles-machinery', 'Machinery Distributor', 'cnc-machining', 'St', 'North American distributor for Homag, Weinig, and other European woodworking machinery lines.', 'https://www.stilesmachinery.com', '616-698-7500', 'info@stilesmachinery.com', '3944 Broadmoor Ave SE, Grand Rapids, MI 49512', 4.7, 421, '{"✓ Verified","Distributor"}'::text[], true, true),
  ('Columbia Forest Products', 'columbia-forest-products', 'Plywood & Veneers', 'wood-species', 'Co', 'Largest North American maker of hardwood plywood and decorative veneers. PureBond formaldehyde-free technology.', 'https://www.columbiaforestproducts.com', '800-237-2428', 'info@cfpwood.com', '222 SW Columbia St, Portland, OR 97201', 4.8, 534, '{"✓ Verified","Manufacturer"}'::text[], true, true),
  ('Roseburg Forest Products', 'roseburg-forest-products', 'Panels & Lumber', 'wood-species', 'Ro', 'Oregon-based producer of plywood, particleboard, MDF, LVL, and engineered lumber products.', 'https://www.roseburg.com', '800-245-1115', 'sales@rfpco.com', '3660 Gateway St, Springfield, OR 97477', 4.6, 378, '{"✓ Verified","Manufacturer"}'::text[], true, true),
  ('Baillie Lumber', 'baillie-lumber', 'Hardwood Lumber', 'wood-species', 'Ba', 'One of the largest Appalachian hardwood distributors. Full species range, kiln-dried, graded lumber worldwide.', 'https://www.baillie.com', '800-950-2850', 'info@baillie.com', '4002 Legion Dr, Hamburg, NY 14075', 4.7, 412, '{"✓ Verified","Distributor"}'::text[], true, true),
  ('M.L. Campbell', 'ml-campbell', 'Finishes & Coatings', 'finishing-coatings', 'MC', 'Professional wood finishing — conversion varnish, lacquer, stains, and water-based coatings for production shops.', 'https://www.mlcampbell.com', '800-364-1359', 'info@mlcampbell.com', '2100 Huntingdon Ave, Waynesboro, PA 17268', 4.8, 689, '{"⭐ Silver Sponsor","✓ Verified","Manufacturer"}'::text[], true, true),
  ('Sherwin-Williams Industrial Wood', 'sherwin-williams-industrial-wood', 'Finishes & Coatings', 'finishing-coatings', 'SW', 'Industrial wood coatings — water-based, UV, conversion varnish, and precatalyzed lacquer systems.', 'https://industrial.sherwin-williams.com/na/us/en/general-industrial/wood-coatings.html', '800-474-3794', 'industrialwood@sherwin.com', '101 W Prospect Ave, Cleveland, OH 44115', 4.6, 523, '{"✓ Verified","Manufacturer"}'::text[], true, true),
  ('Chemcraft', 'chemcraft', 'Finishes & Coatings', 'finishing-coatings', 'Ch', 'Axalta-owned industrial wood finish brand. Conversion varnishes, lacquers, and waterbornes used in cabinet and furniture production.', 'https://www.axalta.com/industrial-wood/us/en_US.html', '800-227-1957', 'chemcraft@axalta.com', '2400 Old Brevard Rd, High Point, NC 27263', 4.7, 356, '{"✓ Verified","Manufacturer"}'::text[], true, true),
  ('Rockler Commercial', 'rockler-commercial', 'Tools & Supplies', null, 'Rk', 'Hardware, tools, specialty supplies. Commercial division serves pro shops with bulk pricing and account support.', 'https://www.rockler.com/commercial', '800-376-7856', 'commercial@rockler.com', '4365 Willow Dr, Medina, MN 55340', 4.5, 278, '{"✓ Verified","Retailer"}'::text[], true, true),
  ('Woodworker''s Supply', 'woodworkers-supply', 'Tools & Supplies', null, 'WS', 'Long-running national mail-order source for tools, hardware, finishing supplies, and machinery.', 'https://www.woodworker.com', '800-645-9292', 'info@woodworker.com', '1108 N Glenn Rd, Casper, WY 82601', 4.4, 198, '{"✓ Verified","Retailer"}'::text[], true, true)
on conflict (slug) do update set name = excluded.name, category = excluded.category, trade = excluded.trade, logo_initials = excluded.logo_initials, description = excluded.description, website = excluded.website, phone = excluded.phone, email = excluded.email, address = excluded.address, rating = excluded.rating, review_count = excluded.review_count, badges = excluded.badges;


-- ------------------------------------------------------------
-- FORUM THREADS (20 threads across categories)
-- author_id left NULL — anonymous seed content
-- IMPORTANT: reply_count is NOT seeded. It starts at 0 and is
-- maintained by the bump_thread_on_post trigger as real posts
-- are inserted (see seed-users-and-posts.sql). Previously we
-- seeded fake counts (47, 62, 127) that never matched the actual
-- forum_posts rows, so threads displayed inflated numbers.
-- ------------------------------------------------------------
insert into public.forum_threads (category_id, title, slug, is_pinned, is_locked, is_solved, view_count, last_reply_at) values
  ('cabinet-making', 'Frameless vs face-frame for a production shop — what''s your take in 2026?', 'frameless-vs-face-frame-2026', false, false, false, 3842, now() - interval '2 hours'),
  ('cabinet-making', 'Best approach for undermount drawer slides on 3/4 ply boxes', 'undermount-slides-3-4-ply-boxes', false, false, true, 1523, now() - interval '1 day'),
  ('architectural-millwork', 'AWI Custom grade vs Premium grade — actual cost delta on a 40k job', 'awi-custom-vs-premium-40k-job', true, false, false, 5127, now() - interval '5 hours'),
  ('architectural-millwork', 'Wainscoting panel layout math — getting the reveal right on a long wall', 'wainscoting-layout-reveal-long-wall', false, false, true, 978, now() - interval '3 days'),
  ('finishing-coatings', 'Switched from CV to waterborne — six months in, here''s what I learned', 'cv-to-waterborne-six-months-in', false, false, false, 4201, now() - interval '8 hours'),
  ('finishing-coatings', 'Fisheye on white pigmented CV — shop air or contaminated product?', 'fisheye-on-white-pigmented-cv', false, false, true, 2108, now() - interval '2 days'),
  ('wood-species', 'Sourcing rift-sawn white oak at scale — who''s your go-to in 2026?', 'rift-white-oak-sourcing-2026', false, false, false, 1876, now() - interval '1 day'),
  ('wood-species', 'Moisture content variance on imported Euro beech — acceptable range?', 'moisture-content-euro-beech-range', false, false, false, 734, now() - interval '4 days'),
  ('hardware', 'Blum Movento vs Grass Dynapro vs Salice Futura — honest comparison', 'blum-vs-grass-vs-salice-drawer-slides', true, false, false, 7234, now() - interval '1 hour'),
  ('hardware', 'Aventos HF failures on heavy MDF doors — weight spec confusion', 'aventos-hf-heavy-mdf-door-failures', false, false, true, 1345, now() - interval '2 days'),
  ('cnc-routers', 'Nesting software shootout — Alphacam, Cabinet Vision CAM, Mozaik, or Enroute?', 'nesting-software-shootout-2026', false, false, false, 3978, now() - interval '6 hours'),
  ('cnc-routers', 'Spoilboard flattening interval on a 5x10 Biesse Rover — how often?', 'spoilboard-flattening-biesse-rover', false, false, true, 1872, now() - interval '3 days'),
  ('edge-banders', 'Edgebander glue pot temp drift — troubleshooting an IDM 200', 'edgebander-glue-pot-drift-idm-200', false, false, false, 612, now() - interval '5 days'),
  ('software-tools', 'Cabinet Vision vs Microvellum for a 15-person shop — which scales better?', 'cabinet-vision-vs-microvellum-15-person', false, false, false, 4512, now() - interval '4 hours'),
  ('estimating', 'How do you price field measures and design time on residential kitchens?', 'pricing-field-measure-design-kitchens', true, false, false, 3201, now() - interval '10 hours'),
  ('hiring-workforce', 'Apprentice pay scales — what are you offering new hires in 2026?', 'apprentice-pay-2026', false, false, false, 2189, now() - interval '1 day'),
  ('standards-codes', 'CARB Phase 2 vs TSCA Title VI — what actually applies to residential millwork?', 'carb-vs-tsca-residential-millwork', false, false, true, 1456, now() - interval '3 days'),
  ('safety-dust', 'Dust collection sizing for a new 8000 sq ft shop — central vs zoned', 'dust-collection-new-8000-sq-ft-shop', false, false, false, 987, now() - interval '2 days'),
  ('show-tell', 'Just finished: 32-door quartersawn white oak kitchen with fluted inset panels', 'finished-32-door-qswo-kitchen', false, false, false, 5834, now() - interval '3 hours'),
  ('industry-news', 'Cabinetmakers Association is folding into AWI — official as of March', 'cma-folding-into-awi-march-2026', false, false, false, 8921, now() - interval '30 minutes')
on conflict (slug) do update set title = excluded.title, category_id = excluded.category_id, is_pinned = excluded.is_pinned, is_solved = excluded.is_solved, view_count = excluded.view_count, last_reply_at = excluded.last_reply_at;


-- ------------------------------------------------------------
-- JOBS (20 openings)
-- ------------------------------------------------------------
-- Use content-hash-style slug in title to dedupe via (title, company) — but the table has no slug.
-- We dedupe by (title, company) using a unique-ish where clause pattern.
-- Simpler: delete prior seed rows by company label, then re-insert.
delete from public.jobs where company in (
  'Heartwood Cabinetry','Meridian Millwork','Cascadia Cabinet Co.','Summit Architectural Woodwork',
  'Ironwood Custom','Keystone Casework','Maple Ridge Cabinetry','Copper State Millwork',
  'Pacific Crest Cabinets','Hudson Valley Woodworks','Riverbend Millwork','Stonewall Custom Cabinetry',
  'Great Lakes Architectural','Sierra Fine Cabinetry','Granite State Millwork','Bayside Cabinet Works',
  'Tall Timber Custom','Foundry Millwork','Cardinal Cabinetry','Appalachian Architectural Woodwork'
);

insert into public.jobs (title, company, location, trade, employment_type, salary_min, salary_max, salary_period, description, requirements, benefits, apply_url, apply_email, is_approved, posted_at) values
  ('CNC Programmer / Operator', 'Heartwood Cabinetry', 'Grand Rapids, MI', 'cnc-machining', 'full-time', 62000, 85000, 'year', 'Program and run our 5x12 Biesse Rover B FT and Thermwood M45. Generate nests in Alphacam, run toolpath verification, manage spoilboard maintenance, and work with the shop floor on optimizing cycle times.', 'Minimum 3 years CNC programming experience, Alphacam or equivalent CAM software, comfortable reading shop drawings and cut lists, able to lift 50 lbs.', 'Full medical/dental/vision, 401k with 4% match, 2 weeks PTO to start, paid holidays, boot and tool allowance.', null, 'careers@heartwoodcabinetry.com', true, now() - interval '2 days'),
  ('Architectural Millwork Estimator', 'Meridian Millwork', 'Dallas, TX', 'business-estimating', 'full-time', 78000, 110000, 'year', 'Perform takeoffs on commercial bid packages, build estimates in Microvellum, coordinate with PMs on scope, pricing, and schedule. Typical projects $250k–$4M.', '5+ years estimating commercial architectural millwork, Microvellum or Innergy experience, strong Excel, ability to read full construction documents.', 'Medical, dental, vision, 3 weeks PTO, 401k match, remote 1 day/week after 90 days.', 'https://meridianmillwork.com/careers', null, true, now() - interval '4 days'),
  ('Journeyman Cabinetmaker', 'Cascadia Cabinet Co.', 'Portland, OR', 'cabinet-making', 'full-time', 30, 42, 'hour', 'High-end residential cabinet shop looking for an experienced bench hand who can move between machining, assembly, and shop installs. Frameless European construction, solid wood doors and drawers, occasional on-site finishing.', 'Journeyman-level — can run a panel saw, edgebander, line borer, and assemble a kitchen front to back. Finish carpentry experience a plus.', 'Top-of-market hourly, health care stipend, simple IRA match, 10 paid holidays, flexible scheduling.', null, 'hiring@cascadiacabinet.com', true, now() - interval '1 day'),
  ('Shop Foreman', 'Summit Architectural Woodwork', 'Denver, CO', 'shop-management', 'full-time', 85000, 120000, 'year', 'Run the floor of a 12-person architectural millwork shop. Scheduling, QC, mentoring, machine maintenance planning, production reporting to ownership.', '10+ years in architectural millwork, 3+ years in a lead or foreman role, AWI QCP familiarity, calm under pressure.', 'Full benefits, 4 weeks PTO, annual bonus tied to shop margin, truck allowance.', 'https://summitaw.com/jobs', null, true, now() - interval '6 days'),
  ('Spray Finisher', 'Ironwood Custom', 'Nashville, TN', 'finishing-coatings', 'full-time', 25, 34, 'hour', 'Conversion varnish and waterborne finishing on cabinet and furniture grade work. Work in a temperature-controlled booth with downdraft flow, flash-off area, and forced-air drying.', '3+ years professional spray experience, pigmented CV and clear finishes, able to tint to sample, Kremlin AAA familiarity a plus.', 'Medical/dental, paid vacation, respirator program and PPE provided, quarterly bonuses.', null, 'work@ironwoodcustom.com', true, now() - interval '3 days'),
  ('Project Manager — Commercial Casework', 'Keystone Casework', 'Harrisburg, PA', 'business-estimating', 'full-time', 82000, 115000, 'year', 'Own 4–6 active commercial casework projects in healthcare, education, and corporate sectors. Submittals, RFIs, shop drawings coordination, installation scheduling.', 'Minimum 5 years PM experience in architectural millwork or GC environment, AutoCAD/Revit literacy, strong schedule and budget ownership.', 'Health insurance, dental, vision, 401k, 3 weeks PTO, vehicle allowance.', 'https://keystonecasework.com/careers', null, true, now() - interval '5 days'),
  ('Cabinet Installer', 'Maple Ridge Cabinetry', 'Burlington, VT', 'cabinet-making', 'full-time', 28, 38, 'hour', 'Residential kitchen and built-in installs across VT, NH, and northern MA. Drive a shop-supplied truck, lead a 2-person crew, handle scribing and site finish touch-ups.', '5+ years installing custom cabinets, clean driving record, own hand tools, ability to problem-solve on-site.', 'Per diem for overnight jobs, truck + fuel provided, paid vacation, health insurance stipend.', null, 'jobs@mapleridgecab.com', true, now() - interval '7 days'),
  ('Entry-Level Cabinetmaker / Apprentice', 'Copper State Millwork', 'Phoenix, AZ', 'cabinet-making', 'apprenticeship', 18, 24, 'hour', 'Structured 3-year apprenticeship program. Rotate through machining, assembly, finishing, and installation. Paid classroom hours and mentoring with a journeyman lead.', 'No experience required. Reliable, curious, willing to learn. High school diploma or GED.', 'Paid training, structured raises, tool program, medical, 401k after 1 year.', 'https://copperstatemillwork.com/apprenticeship', null, true, now() - interval '10 days'),
  ('Wood Finisher — Lead', 'Pacific Crest Cabinets', 'Seattle, WA', 'finishing-coatings', 'full-time', 75000, 95000, 'year', 'Lead a 3-person finishing department on high-end residential work. Own the schedule, QC, color development, and finish specifications for every project.', '7+ years professional finishing, 2+ in a lead role, comfortable developing custom stain and color formulas, strong on safety and ventilation.', 'Full benefits, 3 weeks PTO, respirator fit testing and medical, profit sharing.', null, 'hire@pacificcrestcab.com', true, now() - interval '2 days'),
  ('Sales & Design Consultant — Kitchen & Bath', 'Hudson Valley Woodworks', 'Kingston, NY', 'business-estimating', 'full-time', 55000, 110000, 'year', 'Client-facing role: consult with homeowners and designers, develop designs in 2020 Design, produce quotes and contracts, manage project through to installation.', '3+ years in kitchen/bath design sales, 2020 or KCD experience, portfolio of completed projects, great communication.', 'Base + commission, health insurance, paid vacation, design allowance.', 'https://hudsonvalleyww.com/careers', null, true, now() - interval '8 days'),
  ('Edgebander Operator', 'Riverbend Millwork', 'Cincinnati, OH', 'cnc-machining', 'full-time', 22, 30, 'hour', 'Run our Homag Ambition 1440 and SCM Olimpic K 360. Setup for PVC, ABS, wood veneer, and solid-wood edging. Daily cleaning and glue-pot maintenance.', '2+ years edgebander experience, comfortable with tape, coil, and solid-wood edges, basic mechanical aptitude for setup changes.', 'Medical/dental, 401k, paid vacation, overtime available.', null, 'careers@riverbendmw.com', true, now() - interval '4 days'),
  ('CAD Drafter / Engineered Drawings', 'Stonewall Custom Cabinetry', 'Charlotte, NC', 'business-estimating', 'full-time', 58000, 78000, 'year', 'Produce shop drawings, cut lists, and installation drawings in Cabinet Vision. Coordinate with PMs and the CNC programmer on engineered files.', '3+ years producing cabinet shop drawings, Cabinet Vision proficient, familiarity with dowel and LockDowel construction methods.', 'Medical, dental, 401k match, 2 weeks PTO, hybrid after probation.', 'https://stonewallcab.com/jobs', null, true, now() - interval '3 days'),
  ('Plant Manager', 'Great Lakes Architectural', 'Chicago, IL', 'shop-management', 'full-time', 125000, 165000, 'year', 'Own production of a 45,000 sq ft architectural millwork plant. ~30 FTE. Responsible for throughput, quality, safety, and continuous improvement.', '10+ years in millwork production leadership, AWI familiarity, lean manufacturing background, strong P&L ownership.', 'Executive benefits package, bonus, equity opportunity, relocation assistance.', null, 'execsearch@greatlakesam.com', true, now() - interval '12 days'),
  ('Custom Door & Drawer Maker', 'Sierra Fine Cabinetry', 'Reno, NV', 'cabinet-making', 'full-time', 26, 36, 'hour', 'Dedicated door and drawer cell — 5-piece, MDF, slab, shaker, glass doors. Run a dedicated shaper, coping sled, and drawer box rig.', '3+ years making cabinet doors and drawers, able to set up cope-and-stick tooling, strong attention to repeatable quality.', 'Medical, dental, paid time off, shop-sponsored training, overtime available.', null, 'jobs@sierrafinecab.com', true, now() - interval '5 days'),
  ('Architectural Millwork Installer', 'Granite State Millwork', 'Manchester, NH', 'cabinet-making', 'full-time', 30, 45, 'hour', 'Commercial install crews — healthcare, courtrooms, corporate. Paneling, reception desks, high-end casework. Travel across New England.', 'Minimum 5 years commercial millwork install, foreman-level ability preferred, clean driving record, OSHA 10 minimum.', 'Per diem, travel pay, truck provided, full benefits, 401k match.', 'https://graniteaw.com/careers', null, true, now() - interval '6 days'),
  ('Shop Apprentice — Night Shift', 'Bayside Cabinet Works', 'Tampa, FL', 'cabinet-making', 'part-time', 17, 22, 'hour', 'Night-shift assembly and prep work. Great entry-level role for someone looking to learn the trade while working another job or going to school.', 'Dependable, teachable, able to work 5pm–1am Mon–Thu, ok being on your feet all shift.', 'Shift differential, paid training, uniforms provided, meals on long shifts.', null, 'work@baysidecab.com', true, now() - interval '1 day'),
  ('Finishing Shop Lead', 'Tall Timber Custom', 'Boise, ID', 'finishing-coatings', 'full-time', 72000, 92000, 'year', 'Run a 2-booth finishing department specializing in high-end furniture and architectural millwork. Color matching, finish engineering, QC, and PPE program ownership.', '5+ years finishing, 2+ in a lead role, strong on lacquer and waterborne systems, able to interpret architect finish specs.', 'Top-of-market pay, medical, dental, respirator program, tool allowance.', null, 'careers@talltimbercustom.com', true, now() - interval '8 days'),
  ('IT / Shop Systems Administrator', 'Foundry Millwork', 'Pittsburgh, PA', 'shop-management', 'full-time', 78000, 105000, 'year', 'Own our shop-floor IT: CNC network, file server, estimating/ERP system, barcode stations, and design software deployment. Hybrid role — 3 days on-site.', 'IT infrastructure background, familiarity with Cabinet Vision or Microvellum a strong plus, comfortable around machinery.', 'Medical, dental, vision, 401k match, 3 weeks PTO, hybrid schedule.', 'https://foundrymillwork.com/jobs', null, true, now() - interval '15 days'),
  ('Carving & CNC Artist', 'Cardinal Cabinetry', 'St. Louis, MO', 'cnc-machining', 'contract', 35, 55, 'hour', 'Project-based contract: carve ornamental elements for a hospitality build (corbels, capitals, medallions). Initial run ~120 pieces over 10 weeks.', 'Proven CNC 3D carving portfolio, Aspire or ArtCAM experience, supply own model files, comfortable with select hardwoods.', 'Contract rate, flexible schedule, shop time available for setup and finishing if needed.', null, 'procurement@cardinalcab.com', true, now() - interval '9 days'),
  ('Wood Shop Teacher — Evening Adult Program', 'Appalachian Architectural Woodwork', 'Asheville, NC', 'cabinet-making', 'part-time', 32, 45, 'hour', 'Teach a 12-week evening adult-education woodworking program through our community shop. Two nights/week, project-based curriculum.', 'Professional woodworking background, teaching or mentoring experience preferred, able to design a progressive curriculum.', 'Flexible hours, stipend per cohort, full access to the shop outside class, travel reimbursement for local students.', 'https://appalachianaw.com/education', null, true, now() - interval '20 days');


-- ------------------------------------------------------------
-- EVENTS (20)
-- ------------------------------------------------------------
insert into public.events (title, slug, description, event_type, start_date, end_date, location, venue_name, is_online, registration_url, trade, is_approved) values
  ('AWFS Fair 2026', 'awfs-fair-2026', 'The largest woodworking trade show in North America. Machinery, materials, hardware, finishing systems, software, and 20,000+ trade professionals across 200,000 sq ft.', 'trade-show', '2026-07-25 08:00-07', '2026-07-28 17:00-07', 'Las Vegas, NV', 'Las Vegas Convention Center', false, 'https://www.awfsfair.org/register', null, true),
  ('IWF Atlanta 2026', 'iwf-atlanta-2026', 'International Woodworking Fair — every other year in Atlanta. Biggest U.S. showcase of machinery, software, components, and materials.', 'trade-show', '2026-08-23 09:00-04', '2026-08-26 17:00-04', 'Atlanta, GA', 'Georgia World Congress Center', false, 'https://www.iwfatlanta.com', null, true),
  ('AWI Convention 2026', 'awi-convention-2026', 'Architectural Woodwork Institute annual convention. Education tracks, QCP updates, networking with architectural millwork leaders from around the country.', 'conference', '2026-10-14 07:30-05', '2026-10-17 12:00-05', 'Nashville, TN', 'Gaylord Opryland Resort', false, 'https://www.awinet.org/convention', 'millwork-moulding', true),
  ('KBIS 2026', 'kbis-2026', 'Kitchen & Bath Industry Show, co-located with IBS. Major venue for kitchen designers, fabricators, and cabinet showrooms.', 'trade-show', '2026-02-17 09:00-05', '2026-02-19 17:00-05', 'Orlando, FL', 'Orange County Convention Center', false, 'https://www.kbis.com', 'cabinet-making', true),
  ('Cabinet Vision Fall Summit 2026', 'cabinet-vision-fall-summit-2026', 'Hexagon/Cabinet Vision user conference — training, roadmap, customer showcases, and hands-on labs.', 'conference', '2026-10-05 08:00-04', '2026-10-07 17:00-04', 'Nashville, TN', 'Music City Center', false, 'https://cabinetvision.com/summit', 'cnc-machining', true),
  ('Microvellum User Conference 2026', 'microvellum-user-conference-2026', 'Annual gathering of Microvellum users — deep-dive sessions on engineering, rules, and CAM integration.', 'conference', '2026-09-15 08:00-07', '2026-09-17 15:00-07', 'Ogden, UT', 'Little America Hotel', false, 'https://www.microvellum.com/conference', 'cnc-machining', true),
  ('Wood Industry Sustainability Summit', 'wood-industry-sustainability-summit-2026', 'CARB, TSCA, FSC, and circular-economy conversations for panel producers, cabinet manufacturers, and specifiers.', 'conference', '2026-05-12 08:30-04', '2026-05-13 16:00-04', 'Washington, DC', 'Marriott Marquis', false, 'https://woodsustainability.org/summit', null, true),
  ('Cabinets Makers Association — Eastern Regional', 'cma-eastern-regional-2026', 'Regional meet-up — shop tours, peer-to-peer pricing discussion, workforce panel. Lunch included.', 'meetup', '2026-06-04 08:00-04', '2026-06-04 16:00-04', 'Richmond, VA', 'Meridian Millwork HQ', false, 'https://cabinetmakers.org/eastern-2026', 'cabinet-making', true),
  ('Lean Manufacturing for Custom Shops (Virtual)', 'lean-manufacturing-custom-shops-virtual', 'Two half-day online sessions on applying lean principles to small and mid-sized custom shops without killing the craft.', 'workshop', '2026-03-17 10:00-04', '2026-03-18 13:00-04', null, null, true, 'https://woodworkcareer.org/lean-2026', 'shop-management', true),
  ('Finishing Bootcamp — M.L. Campbell Training Center', 'finishing-bootcamp-mlcampbell-2026', 'Three-day intensive on spray finishing, conversion varnish, waterborne, and troubleshooting defects. Hands-on in an actual shop booth.', 'workshop', '2026-04-21 08:00-04', '2026-04-23 16:00-04', 'Waynesboro, PA', 'M.L. Campbell Technical Center', false, 'https://www.mlcampbell.com/training', 'finishing-coatings', true),
  ('Installation Best Practices Clinic', 'installation-best-practices-clinic-2026', 'One-day intensive for cabinet installers — scribing, shimming, stone-top coordination, and punch-list management.', 'workshop', '2026-05-08 08:00-04', '2026-05-08 16:00-04', 'Columbus, OH', 'Ohio Craftsman Center', false, 'https://ohiocraftsman.com/install-clinic', 'cabinet-making', true),
  ('Estimating Masterclass (Virtual, 4 sessions)', 'estimating-masterclass-virtual-2026', 'Four weekly 2-hour virtual sessions on building an estimating framework for custom and architectural work. Workbook included.', 'workshop', '2026-06-10 13:00-04', '2026-07-01 15:00-04', null, null, true, 'https://woodworkcareer.org/estimating-2026', 'business-estimating', true),
  ('Women in Woodworking — NY Chapter Meetup', 'women-in-woodworking-ny-meetup-2026', 'Quarterly Brooklyn chapter meet-up. Shop tour, light refreshments, open conversation about careers in the trade.', 'meetup', '2026-03-22 18:00-04', '2026-03-22 21:00-04', 'Brooklyn, NY', 'Greenpoint Woodshop Collective', false, 'https://womenwoodworking.org/ny-q1', null, true),
  ('AWI QCP Inspector Training', 'awi-qcp-inspector-training-2026', 'AWI-led certification training for QCP inspectors. Five days, exam included, limited to 24 participants.', 'workshop', '2026-09-21 08:00-05', '2026-09-25 16:00-05', 'Potomac Falls, VA', 'AWI Headquarters', false, 'https://www.awinet.org/qcp-training', 'millwork-moulding', true),
  ('IBS 2026 — Builders'' Show', 'ibs-2026', 'International Builders'' Show — co-located with KBIS. Broader homebuilder crowd but a key venue for cabinet and millwork brands.', 'trade-show', '2026-02-17 09:00-05', '2026-02-19 17:00-05', 'Orlando, FL', 'Orange County Convention Center', false, 'https://www.buildersshow.com', null, true),
  ('Shop Tech Day — CNC Deep Dive', 'shop-tech-day-cnc-deep-dive-2026', 'Hosted by Stiles Machinery — Homag CNC deep dive, nesting best practices, tooling, and preventive maintenance.', 'workshop', '2026-04-02 09:00-04', '2026-04-02 16:00-04', 'Grand Rapids, MI', 'Stiles Machinery Tech Center', false, 'https://www.stilesmachinery.com/tech-day', 'cnc-machining', true),
  ('Young Professionals in the Trade — Annual Retreat', 'yp-trade-retreat-2026', 'Peer retreat for shop owners, managers, and craftspeople under 40. Three days of sessions, shop tours, and networking.', 'conference', '2026-11-03 16:00-07', '2026-11-06 11:00-07', 'Bend, OR', 'The Riverhouse on the Deschutes', false, 'https://yptrade.org/retreat', null, true),
  ('SawStop Safety Training — Certified Shop Program', 'sawstop-safety-training-2026', 'One-day training covering SawStop deployment, maintenance, and broader shop safety culture. Half-day on new contractor vs industrial models.', 'workshop', '2026-03-04 08:00-06', '2026-03-04 16:00-06', 'Tualatin, OR', 'SawStop HQ', false, 'https://www.sawstop.com/training', 'safety-standards', true),
  ('AWFS Emerging Leaders Program', 'awfs-emerging-leaders-2026', 'Selective year-long cohort program for the next generation of industry leaders. Application required; 30 participants.', 'conference', '2026-01-12 09:00-08', '2026-11-06 17:00-08', 'Multiple', 'Rotating — Vegas, Chicago, Atlanta', false, 'https://www.awfsfair.org/emerging-leaders', null, true),
  ('Regional Shop Tour — Midwest Edition', 'regional-shop-tour-midwest-2026', 'Two-day guided tour through 4 well-run Midwest custom shops. Full shop floors, pricing talk, and honest Q&A with owners.', 'meetup', '2026-05-19 08:00-05', '2026-05-20 17:00-05', 'Chicago & Milwaukee', 'Multiple shops', false, 'https://woodworkcareer.org/midwest-tour', null, true)
on conflict (slug) do update set title = excluded.title, description = excluded.description, event_type = excluded.event_type, start_date = excluded.start_date, end_date = excluded.end_date, location = excluded.location, venue_name = excluded.venue_name, is_online = excluded.is_online, registration_url = excluded.registration_url, trade = excluded.trade;


-- ------------------------------------------------------------
-- WIKI ARTICLES (20)
-- ------------------------------------------------------------
insert into public.wiki_articles (title, slug, category, trade, excerpt, body, read_time_minutes, is_published, published_at) values
  ('Introduction to Frameless Cabinet Construction', 'intro-frameless-cabinet-construction', 'Cabinet Making', 'cabinet-making', 'Frameless (European) construction uses a 3/4" panel box with no face frame. This article covers geometry, hardware selection, and common pitfalls.', E'# Introduction to Frameless Cabinet Construction\n\nFrameless cabinet construction — also called "European" or "32mm system" — is the dominant method used in high-production cabinet shops and most modern residential millwork.\n\n## The box\n\nA frameless box is assembled from six 3/4" (18mm or 19mm) panels: two sides, a top, a bottom, a back, and a nailer/stretcher arrangement. The door mounts directly to the edge of the box via European cup hinges.\n\n## 32mm system\n\nAll hardware — hinges, drawer slides, shelf pins — is located on a 32mm grid. Line borers drill this grid in one pass.\n\n## Common pitfalls\n\n- Overlay geometry is trickier than face-frame; bad reveal math shows up on the full wall\n- Hinge selection must match door thickness, weight, and desired overlay\n- Scribes at the wall must be built in, not shimmed later\n\nSee also: [32mm System Explained](/wiki/article/32mm-system-explained), [Hinge Selection Guide](/wiki/article/european-hinge-selection).', 8, true, now() - interval '45 days'),
  ('The 32mm System Explained', '32mm-system-explained', 'Cabinet Making', 'cabinet-making', 'The 32mm system standardizes hardware placement on every frameless box. Here is how it works and why it exists.', E'# The 32mm System Explained\n\nThe 32mm system is the dimensional backbone of European frameless cabinetry. Every hinge, drawer slide, and shelf support lands on a grid of holes 32mm apart.\n\n## Why 32mm?\n\nIt''s a compromise between hole density (more = more adjustability) and panel strength (more holes = weaker panel). 32mm hit the sweet spot when the system was developed in post-war Germany.\n\n## The line borer\n\nA 32mm system requires a line borer — a machine that drills a full column of 5mm holes on 32mm centers in one pass. Modern CNCs do this too.\n\n## Key dimensions to memorize\n\n- 37mm from the front edge to the first hinge cup hole center\n- 37mm from the back edge to the rearmost hole\n- 5mm drill diameter is standard\n', 6, true, now() - interval '40 days'),
  ('European Hinge Selection Guide', 'european-hinge-selection', 'Hardware', 'hardware-accessories', 'How to choose the right European hinge for any door — overlay vs inset, soft-close vs push-to-open, standard vs thick-door.', E'# European Hinge Selection Guide\n\nChoosing the right European hinge comes down to four questions:\n\n1. Overlay, half-overlay, or inset?\n2. Door thickness?\n3. Door weight + count per door?\n4. Soft-close, push-to-open, or standard?\n\n## Overlay, half-overlay, inset\n\nThis is the geometry of the door relative to the cabinet side. Hinge crankage is specified accordingly.\n\n## Door thickness\n\nStandard European hinges assume 3/4" (18mm–19mm) door thickness. For thick doors (1" and up), use a thick-door hinge or face-frame adapter.\n\n## Weight and door count\n\nTwo hinges hold most doors up to about 28 lbs. Add a third above 28 lbs or 48" tall. Always follow the manufacturer''s chart.\n\n## Soft-close\n\nBlum CLIP top BLUMOTION, Hettich Sensys with Silent System, Grass Tiomos — all equivalent in function, different in feel. Pick one and standardize the shop.', 7, true, now() - interval '38 days'),
  ('Understanding AWI Quality Grades', 'awi-quality-grades-explained', 'Architectural Millwork', 'millwork-moulding', 'Economy, Custom, and Premium grades from the Architectural Woodwork Institute — what each grade actually requires and how it affects price.', E'# Understanding AWI Quality Grades\n\nThe Architectural Woodwork Institute (AWI) defines three quality grades for architectural millwork: Economy, Custom, and Premium. Specifying the correct grade is one of the single biggest cost drivers on any bid.\n\n## Economy Grade\n\nRarely specified on commercial work. Minimum visual acceptability, no QCP coverage, most permissive tolerances.\n\n## Custom Grade\n\nThe workhorse grade for the majority of commercial architectural millwork. Tight tolerances, consistent wood grain and color matching, hardware aligned to published standards.\n\n## Premium Grade\n\nEverything Custom requires, plus tighter tolerances, book-matched veneer in most cases, and the most stringent QCP requirements.\n\n## The cost delta\n\nCustom to Premium typically adds 15–30% to the labor and material cost. The key question for estimators is whether the spec genuinely calls for Premium or whether Custom + some key Premium callouts is sufficient.', 9, true, now() - interval '32 days'),
  ('Conversion Varnish vs Waterborne Finish', 'cv-vs-waterborne-finish', 'Finishing', 'finishing-coatings', 'A pragmatic comparison of conversion varnish and modern waterborne systems for production cabinet finishing.', E'# Conversion Varnish vs Waterborne Finish\n\nThis is the most-asked finishing question on the forums. Both systems can produce an excellent cabinet finish. The right choice depends on your shop, your clients, and your regulatory environment.\n\n## Conversion varnish (CV)\n\nTwo-component acid-catalyzed coating. Hard, chemical-resistant, long-term track record on kitchen cabinets.\n\nPros: excellent durability; fast build; strong chemical resistance.\n\nCons: solvent-based, so VOC-limited states restrict usage; respiratory protection required; potential formaldehyde emissions.\n\n## Waterborne\n\nModern waterborne 2K systems (Milesi, M.L. Campbell Agualente Plus, Sherwin-Williams Kem Aqua) rival CV in hardness and clarity.\n\nPros: very low VOC; water cleanup; no blush, no yellowing on most formulas.\n\nCons: film builds slower; requires tighter humidity control; initial hardness takes longer to develop.\n\n## Picking a path\n\nProduction shops in CARB Phase 2 or OTC states have largely moved to waterborne. Custom shops in less-regulated states still run CV daily with no issues. Neither is objectively better — both work.', 8, true, now() - interval '28 days'),
  ('Introduction to CNC Nesting', 'intro-cnc-nesting', 'CNC & Machinery', 'cnc-machining', 'Nesting is the art of arranging cabinet parts on 4x8 sheets to minimize waste and cycle time. Here are the fundamentals.', E'# Introduction to CNC Nesting\n\nNesting is the process of arranging cabinet parts on a sheet of material for efficient cutting on a flatbed CNC. Good nesting reduces material cost and runs faster on the machine.\n\n## Core concepts\n\n- Yield: percentage of sheet area used\n- Grain direction: respects the client''s grain requirement\n- Tool changes: minimized by grouping like operations\n- Onion skin: thin membrane left to hold small parts\n\n## Common software\n\n- Alphacam — general-purpose CAM\n- Cabinet Vision CAM — tightly integrated with Cabinet Vision\n- Mozaik — popular among smaller shops\n- Enroute — used by many signmakers and cabinet shops\n\n## Yield targets\n\nHigh-volume production shops target 85%+ yield on MDF carcass work and 78%+ on veneer plywood with grain constraints.', 7, true, now() - interval '24 days'),
  ('Dust Collection Design Fundamentals', 'dust-collection-design-fundamentals', 'Safety & Shop', 'safety-standards', 'Sizing, ducting, and maintenance basics for woodshop dust collection systems — from a 2-person shop to a full production floor.', E'# Dust Collection Design Fundamentals\n\nDust collection is both a safety requirement and a finish-quality enabler. An undersized or misrouted system causes chronic problems that only get worse with time.\n\n## CFM requirements by machine\n\nEvery machine has a published CFM requirement at a specified static pressure. Sum the simultaneously-running machines and add 10% headroom to size your blower.\n\n## Ducting\n\nMainline sizing follows the total simultaneous CFM; branches step down to each machine. Use 45-degree laterals, not 90s; keep runs short; minimize flex hose.\n\n## Cyclone vs baghouse\n\nCyclones drop the heavy chips before they reach the filters, dramatically extending filter life. Most modern shops run a cyclone.\n\n## Fire suppression\n\nNFPA 664 compliance is increasingly required by AHJs and insurers for shops with >200 lbs of wood dust on-site.', 6, true, now() - interval '22 days'),
  ('Species Guide: Hard Maple', 'species-guide-hard-maple', 'Wood Species', 'wood-species', 'Working properties, appearance, grades, and typical uses of hard (sugar) maple in cabinet and furniture work.', E'# Species Guide: Hard Maple\n\nHard maple (Acer saccharum) is one of the most widely-used domestic hardwoods in North American cabinet and furniture making.\n\n## Appearance\n\nCream to very pale reddish-brown heartwood. Sapwood ranges from off-white to pale yellowish-white. Largely straight grain, often with curl, bird''s eye, or quilted figure.\n\n## Working properties\n\nDense and hard (Janka ~1450). Machines well but can burn easily on routers and shapers — sharp tooling and moderate feed rates are essential.\n\n## Common uses\n\n- Cabinet doors and face frames\n- Butcher block and countertops\n- Furniture, especially painted or opaque-finished\n- Flooring, cutting boards, turnings\n\n## Finishing notes\n\nMaple''s closed grain produces excellent results with waterborne clear finishes. Staining is tricky — the dense grain doesn''t accept pigment evenly. A gel stain or dye-toner-glaze schedule usually delivers better results than pigment stain alone.', 5, true, now() - interval '20 days'),
  ('Species Guide: White Oak', 'species-guide-white-oak', 'Wood Species', 'wood-species', 'Working properties, cut patterns (rift, quartered, plain), and specification guidance for white oak in architectural millwork.', E'# Species Guide: White Oak\n\nWhite oak (Quercus alba) is the most-specified architectural hardwood in the United States. Rift, quartered, and plain-sawn variants each have distinct looks and costs.\n\n## Cut patterns\n\n- Plain-sawn (flat sawn): cathedral-figure grain, most economical\n- Quarter-sawn: tight parallel grain with ray fleck\n- Rift-sawn: tight parallel grain, minimal ray fleck\n\nRift is currently the premium-specified cut in most A-list commercial work.\n\n## Working properties\n\nHard (Janka ~1350), tough, open-pored. Works well with sharp tooling but dulls edges. Glue-up is fine with modern PVAs.\n\n## Specification notes\n\nFor rift white oak, specify the grain angle in the cut list (typically 90° ± 15°). Not all mills can consistently hit a tight rift spec.\n\n## Finishing notes\n\nFumed white oak is back in fashion. Classic rift white oak with a natural clear waterborne delivers the signature "modern farmhouse" look.', 6, true, now() - interval '18 days'),
  ('Cabinet Vision vs Microvellum: Software Comparison', 'cabinet-vision-vs-microvellum', 'Software', 'cnc-machining', 'Honest comparison of the two dominant cabinet shop software platforms — Cabinet Vision (Hexagon) and Microvellum.', E'# Cabinet Vision vs Microvellum\n\nThese two platforms dominate the mid-to-large cabinet shop market. Both do engineering, cut lists, reports, and CNC output. They take very different approaches.\n\n## Cabinet Vision\n\nOwned by Hexagon. Graphical, approachable, faster to get new users productive. Pricing is per-module with an annual subscription. Strong integration with their own CAM.\n\n## Microvellum\n\nFormulaic, rule-based, extremely customizable. Steeper learning curve. Pricing tends to be higher but includes more at the base level. Runs on AutoCAD.\n\n## Which to pick\n\n- 5-person shop doing residential cabinets? Cabinet Vision almost always wins on time-to-value.\n- 40-person architectural shop with complex engineering? Microvellum''s rule engine pays for itself.\n- Already running Mozaik / KCDw and moving upmarket? Evaluate both; the transition path differs.', 6, true, now() - interval '16 days'),
  ('Estimating Custom Cabinet Projects', 'estimating-custom-cabinet-projects', 'Business', 'business-estimating', 'A practical framework for pricing residential custom cabinet work — from bench-made one-offs to full kitchen and built-in packages.', E'# Estimating Custom Cabinet Projects\n\nPricing custom work is where most small shops leave money on the table. A repeatable framework helps.\n\n## Linear-foot pricing (LFP)\n\nCommon shorthand: $ per linear foot of cabinetry. A starting range for custom work in 2026 is $450–$950/LF with a different multiplier for uppers, bases, and tall units.\n\nPros: fast, client-friendly.\n\nCons: doesn''t capture design complexity, species upgrades, or unusual hardware.\n\n## Takeoff + multiplier\n\nFull takeoff of panels, doors, drawers, and hardware. Multiply material cost by a shop-specific labor multiplier (typically 2.5×–4×, depending on scope).\n\n## The honest truth\n\nMost experienced estimators use LFP as a sanity check and a full takeoff as the actual bid. When they disagree by more than ~15%, something is wrong with one of them.', 7, true, now() - interval '14 days'),
  ('OSHA and Wood Dust: Regulations in Plain Language', 'osha-wood-dust-regulations', 'Safety & Shop', 'safety-standards', 'The wood dust PEL, OSHA general duty clause, combustible dust hazards, and what an OSHA inspector actually looks for in a woodshop.', E'# OSHA and Wood Dust\n\nWood dust is regulated under multiple OSHA standards. The PEL (permissible exposure limit) for most wood dust is 15 mg/m³ total dust, 5 mg/m³ respirable. Certain species (western red cedar) carry tighter limits.\n\n## General duty clause\n\nOSHA can and does cite shops for combustible dust hazards under the general duty clause, even without a species-specific standard.\n\n## What inspectors look for\n\n- Visible dust accumulation on beams, ducting, and equipment\n- Housekeeping program documentation\n- Dust collection at the point of generation\n- Respirator program compliance (fit tests, medical eval)\n- Electrical equipment in dusty areas (NEC Class II areas)\n\n## Key takeaway\n\nIf you can write your name in the dust on a beam, you''re at risk of both a citation and a deflagration.', 5, true, now() - interval '12 days'),
  ('CARB Phase 2 and TSCA Title VI: What You Need to Know', 'carb-tsca-overview', 'Standards & Codes', 'safety-standards', 'Formaldehyde emissions rules for composite wood products — plywood, particleboard, and MDF — and how they affect cabinet shops.', E'# CARB Phase 2 and TSCA Title VI\n\nCARB Phase 2 is California''s air-quality regulation on formaldehyde emissions from composite wood products. TSCA Title VI is the federal EPA regulation that adopted essentially the same limits nationwide.\n\n## What products are covered\n\n- Hardwood plywood (HWPW)\n- Particleboard (PB)\n- Medium-density fiberboard (MDF)\n- Thin MDF\n\n## Emission limits\n\nFormaldehyde: 0.05 ppm HWPW, 0.09 ppm PB, 0.11 ppm MDF, 0.13 ppm thin MDF.\n\n## What cabinet shops must do\n\n- Buy only compliant (labeled) composite wood products\n- Keep invoices for three years\n- Label finished goods when selling direct to consumers\n\nMajor panel suppliers (Columbia Forest Products, Roseburg, Uniboard, Arauco) ship compliant products by default.', 6, true, now() - interval '10 days'),
  ('Finishing Defects: Causes and Cures', 'finishing-defects-causes-cures', 'Finishing', 'finishing-coatings', 'Fisheye, orange peel, blush, crater, pinhole, sag — what causes them and how to prevent recurrence in a production finishing environment.', E'# Finishing Defects: Causes and Cures\n\nMost finishing defects trace back to one of four root causes: contamination, environmental conditions, technique, or product formulation.\n\n## Fisheye\n\nRound craters in the film. Cause: silicone contamination. Cure: fish-eye eliminator additive; track down the silicone source (cutting oil on CNC, a new hand lotion, someone''s boot polish).\n\n## Orange peel\n\nStippled, textured surface. Cause: improper atomization, too-high viscosity, or too-fast flash-off. Cure: thin per spec, slow down, double-check gun pressure.\n\n## Blush\n\nMilky haze in the film. Cause: trapped moisture. Cure: raise booth temperature, reduce humidity, add a slower solvent.\n\n## Pinholes\n\nTiny holes, usually in a thick film. Cause: trapped solvent or air exiting too quickly. Cure: apply in thinner coats, allow longer flash-off.\n\n## Sag\n\nDrips or curtains on a vertical surface. Cause: too-wet application. Cure: lighter coats, better gun technique, thinner product.', 7, true, now() - interval '8 days'),
  ('Commercial Casework: Plastic Laminate Construction', 'commercial-casework-plam-construction', 'Architectural Millwork', 'millwork-moulding', 'Building commercial plastic-laminate casework to AWI standards — substrate, laminate selection, edge treatment, and installation.', E'# Commercial Casework: Plastic Laminate Construction\n\nHigh-pressure laminate (HPL) casework is the workhorse of commercial millwork — schools, healthcare, libraries, offices.\n\n## Substrate\n\nIndustrial-grade particleboard (45 lb density or better) is standard. MDF for tightly curved or detailed edges. Plywood for wet areas.\n\n## Laminate selection\n\nWilsonart, Formica, and Pionite are the big three. Specify finish (matte, satin, suede) per the spec, and always backer the opposite face to prevent warping.\n\n## Edge treatment\n\nSelf-edge laminate is common but shows a brown line. PVC 3mm edge (laser or glue) is now standard on most commercial work. Solid-wood edges for premium specs.\n\n## Installation\n\nAll fasteners concealed. Scribes at walls must be shop-built or field-scribed with a trim cap. Coordinate with plumbing and electrical cutouts on the shop drawing.', 6, true, now() - interval '7 days'),
  ('Cabinet Door Styles: A Visual Glossary', 'cabinet-door-styles-glossary', 'Cabinet Making', 'cabinet-making', 'Shaker, slab, raised-panel, recessed-panel, inset, mullion, fluted, reeded — a concise visual glossary of cabinet door styles.', E'# Cabinet Door Styles: A Visual Glossary\n\n## Shaker\n\nFlat recessed center panel in a 5-piece frame. Simple, timeless, and the single most-specified residential cabinet door since 2015.\n\n## Slab\n\nOne-piece flat door — MDF with an applied finish, thermofoil, melamine, or veneer.\n\n## Raised panel\n\nCenter panel rises from the frame via a profile cope. The visual signature of traditional residential cabinetry.\n\n## Recessed panel\n\nCenter panel sits below the face of the frame. Softer visual than shaker but still contemporary.\n\n## Mullion\n\nFrame with glass panels subdivided by muntins. Often used for display cabinets and uppers flanking a range.\n\n## Fluted / Reeded\n\nVertical grooves (flutes, concave) or ridges (reeds, convex) across the face of a slab door. Strong 2020s aesthetic.', 4, true, now() - interval '6 days'),
  ('Moisture Content and the Cabinet Shop', 'moisture-content-cabinet-shop', 'Wood Species', 'wood-species', 'Why moisture content matters, how to measure it, and what targets a production cabinet shop should hit at each stage.', E'# Moisture Content and the Cabinet Shop\n\nMoisture content (MC) is the single most important variable in wood movement. Ignore it and you will chase warping, cracking, and failed joints forever.\n\n## Target MC by application\n\n- Interior millwork (most of the U.S.): 6–8%\n- Interior millwork (Southwest/arid): 4–6%\n- Interior millwork (humid Southeast/Gulf): 9–11%\n- Exterior work: 12–15%\n\n## Measuring\n\nPin meter for spot checks. Pinless for non-destructive reads. Both need to be calibrated for species and thickness.\n\n## Acclimation\n\nBring lumber into the shop at least 5 days before machining, stickered for airflow. Re-check MC before committing to expensive material.\n\n## What goes wrong\n\nBuild a large solid-wood panel at 12% MC and install it in a home at 6% MC. The panel will shrink ~1% per 5% MC change. On a 24" panel, that''s enough to split a frame.', 5, true, now() - interval '5 days'),
  ('Hiring Your First Apprentice', 'hiring-first-apprentice', 'Business', 'shop-management', 'A practical guide for shop owners hiring their first apprentice — finding candidates, structuring the role, paying fairly, and retaining talent.', E'# Hiring Your First Apprentice\n\nThe workforce pipeline is the hardest problem most small shops face. The good news: apprentices are out there, they just need a well-structured role.\n\n## Where to find candidates\n\n- Local technical colleges and trade programs\n- High school career fairs\n- Social media (Instagram reels of your shop beat every job board)\n- Your best customers — they often know someone\n\n## Structuring the role\n\nDocument the first year in writing: what they will learn, how raises are earned, how progress is reviewed. This is the #1 reason apprentices quit — ambiguity.\n\n## Paying fairly\n\n2026 starting pay for a no-experience apprentice ranges from $18/hr in lower-cost regions to $24/hr in high-cost metros. Plan structured increases at 6, 12, and 24 months.\n\n## Retaining\n\nPay mattered, but culture matters more. The shops with the best apprentice retention all share one thing: the owner is on the floor, mentoring daily.', 6, true, now() - interval '4 days'),
  ('Running a Profitable Custom Shop', 'running-profitable-custom-shop', 'Business', 'shop-management', 'Margins, overhead, effective hourly rate, and the numbers every custom cabinet shop owner should watch monthly.', E'# Running a Profitable Custom Shop\n\nMost custom shops run on gut and instinct. The ones that survive a down market watch a small set of numbers every month.\n\n## Gross margin\n\nRevenue minus direct materials and direct labor, divided by revenue. A healthy custom cabinet shop runs 38–48% gross margin.\n\n## Overhead absorption\n\nAll the fixed costs — rent, utilities, equipment, admin — divided by billable shop hours. This is your shop rate floor.\n\n## Effective hourly rate (EHR)\n\nTotal revenue divided by total billable shop hours. Trending EHR is your single best early warning of pricing problems.\n\n## The owner trap\n\nThe owner-operator who charges themselves $40/hr in their estimates but nets $12/hr after overhead is the most common small-shop failure mode. Pay yourself the shop rate in the books, even if you re-invest it.\n\n## Monthly review\n\nOne hour per month, the same morning every month. Margins, backlog, AR aging, pipeline. Ninety minutes that saves most shops from slow-motion failure.', 8, true, now() - interval '3 days'),
  ('Modern Drawer Box Construction', 'modern-drawer-box-construction', 'Cabinet Making', 'cabinet-making', 'Dovetail vs dowel vs LockDowel vs French-dovetail, 1/2" vs 5/8" vs 3/4" sides — a pragmatic comparison of current drawer box options.', E'# Modern Drawer Box Construction\n\nDrawer boxes are a small line item that dominates perceived quality. Specify them well and they quietly elevate the project; specify them poorly and you hear about it for years.\n\n## Joinery\n\n- English dovetail: the traditional premium choice\n- French dovetail: common on prefab boxes (Keystone Wood, Crystal)\n- Dowel: fast and strong on the right machines\n- LockDowel: fast, no-clamp-time, popular in production shops\n\n## Material\n\nSolid maple 5/8" sides with a 1/2" bottom is the common premium standard. 1/2" sides save cost on mid-market work. Baltic birch with a melamine bottom is popular in modern contemporary builds.\n\n## Bottom attachment\n\nCaptured bottom (dadoed) is stronger. Applied bottom (screwed or stapled) is easier for production and serviceable later.\n\n## Bought vs shop-made\n\nOutsourcing drawer boxes to a specialty producer (Keystone, Crystal, Northtown) is often cheaper and faster than making them in-house, unless volume justifies a dedicated drawer box cell.', 7, true, now() - interval '2 days')
on conflict (slug) do update set title = excluded.title, category = excluded.category, trade = excluded.trade, excerpt = excluded.excerpt, body = excluded.body, read_time_minutes = excluded.read_time_minutes, is_published = excluded.is_published, published_at = excluded.published_at;


-- ------------------------------------------------------------
-- NEWS ARTICLES (20)
-- ------------------------------------------------------------
insert into public.news_articles (title, slug, category, trade, excerpt, body, source_url, is_published, published_at) values
  ('Cabinet Makers Association to merge into AWI in Q3 2026', 'cma-merges-into-awi-q3-2026', 'Industry', null, 'The long-rumored consolidation between the Cabinet Makers Association and the Architectural Woodwork Institute has been formalized. Operations roll into AWI''s Potomac Falls headquarters in Q3.', E'The Cabinet Makers Association (CMA) and the Architectural Woodwork Institute (AWI) announced a formal merger that will see CMA''s membership, programs, and educational content fold into AWI by Q3 2026.\n\nCMA members will retain their existing membership pricing through 2027. AWI will continue to operate the CMA Cabinets & Closets Expo under its existing brand.\n\nThe combined organization will represent roughly 2,400 member shops across the United States and Canada.', null, true, now() - interval '3 days'),
  ('Hardwood lumber prices stabilize after 18-month decline', 'hardwood-lumber-stabilizes-2026', 'Materials', 'wood-species', 'The NHLA index shows hardwood lumber prices flattening after a sustained decline from 2024 highs.', E'The National Hardwood Lumber Association index of domestic hardwood prices shows a clear flattening of the 18-month decline that began in late 2024.\n\nRed oak, white oak, and hard maple have all held steady for three consecutive months. Cherry and walnut continue to show softness, reflecting shifting design preferences toward rift white oak and natural maple.\n\nMill operators note that sawn log inventories are below five-year averages, which may support modest price increases in late 2026 if demand returns.', null, true, now() - interval '5 days'),
  ('OSHA proposes tightened wood dust PEL', 'osha-proposes-tightened-wood-dust-pel', 'Regulatory', 'safety-standards', 'A Notice of Proposed Rulemaking would lower the wood dust PEL from 15 mg/m³ to 5 mg/m³ total dust. Comment period runs through August.', E'OSHA has published a Notice of Proposed Rulemaking that would lower the permissible exposure limit (PEL) for wood dust from 15 mg/m³ total dust to 5 mg/m³ total dust, with a 2.5 mg/m³ respirable fraction limit.\n\nIf adopted, the rule would dramatically increase compliance costs for shops without modern dust collection infrastructure. Industry associations have signaled they will push for a three-year compliance phase-in.\n\nThe comment period runs through August 2026. Shop owners can submit comments through the federal rulemaking portal.', null, true, now() - interval '6 days'),
  ('Biesse introduces Stream A 4.2 edgebander with AI defect detection', 'biesse-stream-a-42-ai-edgebander', 'Machinery', 'cnc-machining', 'The Italian machinery maker''s latest edgebander integrates a camera-based quality system that flags glue line and edge-banding defects in real time.', E'Biesse has launched the Stream A 4.2, the latest in its high-production edgebander line. The headline feature is an integrated computer vision system that monitors the edge line and flags glue gaps, missed trim, and edge-banding color shift as parts exit the machine.\n\nThe system is positioned as a reduction in downstream QC labor rather than a replacement for experienced operators. Initial installations in Europe have reported a 30–40% reduction in parts flagged at final inspection.\n\nPricing has not been publicly disclosed. Stiles Machinery is the North American distributor.', null, true, now() - interval '9 days'),
  ('Columbia Forest Products expands PureBond plywood capacity', 'columbia-purebond-expands-capacity', 'Materials', 'wood-species', 'A $65M capital investment will add a second PureBond line at the Old Fort, NC mill. Production is expected to come online in Q2 2027.', E'Columbia Forest Products has announced a $65 million capital investment to expand PureBond hardwood plywood capacity at its Old Fort, NC facility. A new production line will effectively double the mill''s output.\n\nPureBond is the company''s formaldehyde-free adhesive technology, introduced in 2005 and now standard across the product line. Demand has grown steadily as specifiers push for low-emission composite wood products.\n\nThe expansion is expected to create roughly 45 new manufacturing positions at the Old Fort site.', null, true, now() - interval '12 days'),
  ('Waterborne finish adoption passes 50% among surveyed shops', 'waterborne-finish-adoption-50-percent', 'Finishing', 'finishing-coatings', 'A Cabinet Makers Association member survey finds 52% of respondents have transitioned from conversion varnish to waterborne as their primary production finish.', E'A Cabinet Makers Association survey of 847 member shops shows 52% now use a waterborne topcoat as their primary production finish — up from 38% two years ago.\n\nThe driver is two-fold: modern waterborne 2K systems have closed the performance gap with conversion varnish, and tightening VOC regulations in key markets (California, New York, Northeast OTC states) have made CV more expensive to use compliantly.\n\nConversion varnish retains a strong foothold in custom furniture and in less-regulated regions, where per-gallon cost and film build remain attractive.', null, true, now() - interval '14 days'),
  ('Canadian softwood lumber tariffs climb to 17.1%', 'canadian-softwood-lumber-17-percent', 'Markets', null, 'The latest U.S. Commerce Department review raises the combined antidumping and countervailing duty rate on Canadian softwood to 17.1%.', E'The U.S. Commerce Department has published the latest administrative review of antidumping and countervailing duties on Canadian softwood lumber. The combined duty rate will rise to 17.1% effective August 1.\n\nThe new rate affects framing lumber, not hardwood. Cabinet and millwork shops consume softwood primarily for jigs, fixtures, and production infrastructure, so the direct impact is limited — but the downstream effect on housing starts is watched closely by the kitchen and bath sector.\n\nU.S. sawmill associations have welcomed the adjustment; Canadian producers have indicated they will appeal.', null, true, now() - interval '15 days'),
  ('Microvellum launches cloud-based pricing module', 'microvellum-launches-cloud-pricing-module', 'Software', 'cnc-machining', 'The long-awaited web-based pricing tool lets sales reps build estimates from a phone or tablet, with approval workflows and real-time inventory awareness.', E'Microvellum has released Cloud Pricing, a web-based estimating front end that connects to the company''s desktop engineering and shop-floor systems.\n\nSales reps can build preliminary pricing from any browser, attach photos and specifications, and route estimates through an approval workflow before promoting them to a full engineered project.\n\nPricing is subscription-based and tied to an existing Microvellum seat count. Early-access customers have reported 30–50% faster turnaround on initial quotes.', null, true, now() - interval '17 days'),
  ('Kitchen & Bath spending forecast lowered for 2026', 'kb-spending-forecast-lowered-2026', 'Markets', 'cabinet-making', 'NKBA has revised its 2026 kitchen and bath spending forecast downward, citing slower housing turnover and consumer caution on large discretionary projects.', E'The National Kitchen & Bath Association has revised its 2026 industry spending forecast downward by approximately 4.2%, now projecting roughly $175B in total kitchen and bath spending.\n\nThe revision reflects slower existing-home sales and continued caution among consumers on large remodels. Dealer-level data shows project sizes trending smaller — more refresh, less full-gut remodel.\n\nForecasts call for a gradual recovery in 2027 as interest rates and housing turnover normalize.', null, true, now() - interval '18 days'),
  ('Blum opens new North American distribution center in Texas', 'blum-new-texas-distribution-center', 'Hardware', 'hardware-accessories', 'The Austrian hardware maker is opening its third North American distribution center, targeting faster ship times to the Southern and Southwestern U.S.', E'Blum has broken ground on a new 180,000 sq ft distribution center in the Dallas-Fort Worth metro area, its third North American logistics hub after Charlotte and Toronto.\n\nThe facility will stock the full range of Blum hinges, drawer systems, and lift systems, and is engineered to ship same-day within the Southern U.S. and next-day to the West Coast.\n\nOperations are expected to begin in early 2027. Blum projects roughly 60 new positions at the site.', null, true, now() - interval '20 days'),
  ('AWI QCP inspections shift fully digital in 2026', 'awi-qcp-fully-digital-2026', 'Standards', 'millwork-moulding', 'The Architectural Woodwork Institute''s Quality Certification Program transitions to a fully digital inspection and reporting system this year.', E'AWI''s Quality Certification Program (QCP) is transitioning to a fully digital inspection workflow in 2026. Inspectors will capture findings on tablets on the jobsite, with photo attachments, and reports will be available to the specifier the same day.\n\nThe move is expected to cut QCP reporting turnaround from 7–10 days to under 48 hours in most cases. Certified shops will have access to a web portal to review all past inspections and findings.\n\nThe rollout will complete by October 2026. Paper reports will remain available on request for clients that require them.', null, true, now() - interval '22 days'),
  ('Thermwood shipping first LSAM installations to furniture makers', 'thermwood-lsam-furniture-shipments', 'Machinery', 'cnc-machining', 'Large-scale additive manufacturing systems — previously marketed to aerospace and marine — are finding a foothold in high-end custom furniture production.', E'Thermwood has delivered its first Large-Scale Additive Manufacturing (LSAM) system specifically configured for furniture production to a mid-Atlantic fabricator.\n\nLSAM systems 3D-print large-format carbon-fiber-reinforced polymer forms that can then be machined to tight tolerances. The technology has been used in aerospace tooling and marine applications; furniture is a new frontier.\n\nThe fabricator intends to produce complex turned, carved, and sculptural forms that would otherwise require extensive hand labor. Thermwood has reported strong interest from architectural fabricators.', null, true, now() - interval '25 days'),
  ('Cabinet Vision 2026 release brings major CAM updates', 'cabinet-vision-2026-release-cam', 'Software', 'cnc-machining', 'The Hexagon-owned design suite ships its 2026 release with substantial CAM improvements, AI-assisted nest optimization, and tighter integration with popular ERP systems.', E'Cabinet Vision 2026 has shipped to customers under the standard annual maintenance program. Headline features include AI-assisted nest optimization, a rebuilt tool library UI, and new ERP connectors for NetSuite, Epicor, and Global Shop Solutions.\n\nThe nest optimizer uses a reinforcement-learning model trained on historical nests to suggest improved part arrangements. Early user reports indicate 3–7% yield improvements on mixed-grain and veneer nests.\n\nExisting customers on active maintenance receive the upgrade at no additional cost.', null, true, now() - interval '28 days'),
  ('Hettich expands U.S. Sensys distribution', 'hettich-expands-sensys-distribution', 'Hardware', 'hardware-accessories', 'The German hardware maker is expanding its Sensys hinge and soft-close drawer system distribution network into three additional U.S. distribution partners.', E'Hettich has signed distribution agreements with three additional U.S. wholesalers for its Sensys hinge and Actro drawer slide lines. The expansion brings total U.S. distribution points to 14.\n\nThe move is positioned as a response to long-running demand for faster local availability of European hardware components. Shop owners in the Mountain West and Upper Midwest have been the most vocal in requesting shorter lead times.\n\nThe new distributors begin stocking in May 2026.', null, true, now() - interval '30 days'),
  ('Custom shop apprentice pay up 8.3% year over year', 'apprentice-pay-up-2026', 'Workforce', 'shop-management', 'A Woodworking Network survey shows apprentice compensation climbing at roughly twice the rate of journeyman pay as shops compete for entry-level talent.', E'Woodworking Network''s 2026 compensation survey shows apprentice-level pay rising 8.3% year-over-year across surveyed shops, roughly double the 4.1% increase reported for journeyman positions.\n\nThe pattern reflects a well-documented workforce pipeline challenge — shops are willing to pay more to secure and retain trainable talent, while journeyman wages remain constrained by what the market can absorb on bid work.\n\nShops that offer structured apprenticeship programs, documented training milestones, and clear paths to full journeyman roles report significantly better retention.', null, true, now() - interval '33 days'),
  ('Felder Group debuts Format-4 profit H400 with revised control', 'felder-format-4-profit-h400-control', 'Machinery', 'cnc-machining', 'The new control software on the profit H400 brings a more contemporary UI, integrated tool library management, and faster cycle setup.', E'Felder Group''s Format-4 brand has introduced a revised control software package on the profit H400 CNC, addressing long-running user complaints about the prior interface.\n\nThe new UI adopts a tile-based touchscreen layout and integrates the tool library with a visual tool preview and parameter editor. Users report setup-to-first-cut times improving by roughly 20%.\n\nExisting H400 customers can upgrade to the new control for a modest fee.', null, true, now() - interval '35 days'),
  ('Fire at Midwest cabinet plant highlights dust suppression gaps', 'midwest-cabinet-plant-fire-dust-suppression', 'Safety', 'safety-standards', 'A weekend fire at an Indiana cabinet plant has been attributed to combustible wood dust. No injuries. Insurance claim expected to be a total loss.', E'A weekend fire at a mid-sized Indiana cabinet plant has been attributed to combustible wood dust in an overhead beam area above the CNC floor. No injuries were reported as the fire occurred outside of shift hours.\n\nThe state fire marshal has indicated that the facility''s active dust suppression system did not extend to the overhead accumulation area, a configuration that remains common in older shops.\n\nNFPA 664 compliance has been a topic of increasing insurer focus. Several national insurers now require NFPA 664 inspection documentation as a precondition of renewal for shops above 10,000 sq ft.', null, true, now() - interval '37 days'),
  ('Wood Industry Resource Council launches free safety toolkit', 'wirc-launches-safety-toolkit', 'Safety', 'safety-standards', 'A new industry-wide initiative releases a free safety toolkit covering dust, ergonomics, respiratory, and training — available to any U.S. shop.', E'The Wood Industry Resource Council has released a free, downloadable safety toolkit covering dust collection, respiratory protection, ergonomics, and training program templates.\n\nThe toolkit includes editable documents (OSHA-style programs, training rosters, inspection checklists) that shops can adopt directly without paying consultant fees.\n\nThe initiative is funded by a consortium of industry associations and machinery makers and is offered at no charge to any U.S. shop.', null, true, now() - interval '40 days'),
  ('Homag reorganizes North American operations', 'homag-reorganizes-north-america', 'Machinery', 'cnc-machining', 'The Homag Group is restructuring its North American operations, consolidating support, parts, and service under a unified team out of Grand Rapids.', E'The Homag Group has announced a reorganization of its North American operations. Technical support, parts, and service functions will consolidate under a unified team out of the Grand Rapids, MI facility.\n\nThe move is positioned as an effort to simplify the experience for end customers — one phone number, one portal, one account team. Customers report mixed reviews on support responsiveness over the past several quarters.\n\nThe restructuring is expected to be complete by Q4 2026. Existing contracts will transition automatically.', null, true, now() - interval '42 days'),
  ('Small shop closures rise in 2025, data shows', 'small-shop-closures-rise-2025', 'Markets', null, 'Dun & Bradstreet data shows woodworking establishment closures up 11% year over year in 2025, concentrated among shops under 10 employees.', E'Dun & Bradstreet business demographic data shows woodworking establishment closures rising 11% year-over-year in 2025, concentrated among shops with fewer than 10 employees.\n\nThe pattern tracks with anecdotal reporting — small shops faced compounded pressure from soft residential demand, finance cost headwinds, and generational transition challenges.\n\nThe data is not all bad: shops in the 20–100 employee band actually grew slightly, reflecting consolidation toward mid-sized operators with the infrastructure to weather a soft market.', null, true, now() - interval '45 days')
on conflict (slug) do update set title = excluded.title, category = excluded.category, trade = excluded.trade, excerpt = excluded.excerpt, body = excluded.body, source_url = excluded.source_url, is_published = excluded.is_published, published_at = excluded.published_at;


-- ------------------------------------------------------------
-- MARKETPLACE LISTINGS (20)
-- ------------------------------------------------------------
insert into public.marketplace_listings (title, slug, category, trade, condition, price, currency, description, location, is_approved, is_sold) values
  ('2019 Biesse Rover B FT 1836 5x12 CNC Router', 'biesse-rover-b-ft-1836-2019', 'CNC Machinery', 'cnc-machining', 'used-excellent', 142500.00, 'USD', '2019 Biesse Rover B FT 1836, 5x12 bed, 12-position ATC, Biesse vacuum, pod-and-rail, Winglet. 4,800 hours. Installed and running until removal. Original owner, full service history available.', 'Grand Rapids, MI', true, false),
  ('SCM Olimpic K 360 Edgebander — Excellent Condition', 'scm-olimpic-k-360-edgebander', 'Edgebanders', 'cnc-machining', 'used-excellent', 38500.00, 'USD', 'SCM Olimpic K 360 edgebander with PVC, ABS, and solid-wood edging capability. Pre-milling, corner rounding, buffing. Low hours, impeccably maintained. Will include tooling package.', 'Columbus, OH', true, false),
  ('Weinig Unimat 23 EL 6-Head Moulder', 'weinig-unimat-23-el-moulder', 'Moulders', 'millwork-moulding', 'used-good', 62000.00, 'USD', 'Weinig Unimat 23 EL 6-head moulder. 7 HP spindles, 22 ft/min feed. Comes with a full set of Weinig tooling and spare parts. Set up and running daily until sale.', 'Birmingham, AL', true, false),
  ('2021 Thermwood M45 3-Axis CNC — 5x10', 'thermwood-m45-3-axis-5x10-2021', 'CNC Machinery', 'cnc-machining', 'used-excellent', 108000.00, 'USD', '2021 Thermwood M45, 5x10 bed, 12-position ATC, Thermwood vacuum, 20 HP spindle. 2,100 hours. Runs daily. Selling to upgrade to 5-axis.', 'Dallas, TX', true, false),
  ('Kremlin Rexson AAA Spray Package — Complete', 'kremlin-rexson-aaa-spray-package', 'Finishing', 'finishing-coatings', 'used-excellent', 4800.00, 'USD', 'Kremlin Rexson 20-C25 AAA air-assisted airless pump with 35-foot hose, pole gun, tip set. Ran waterborne only for the last 18 months. Immaculate condition.', 'Portland, OR', true, false),
  ('Felder KF 700 S Professional Saw-Shaper', 'felder-kf-700-s-saw-shaper', 'Combination', 'cabinet-making', 'used-good', 14500.00, 'USD', 'Felder KF 700 S combination machine — 10" sliding table saw with a shaper on the same table. Outboard spindle, sliding-table crosscut. Ideal for a bench joiner or small shop.', 'Denver, CO', true, false),
  ('Powermatic 20" Planer (Model 209HH) w/ Helical Head', 'powermatic-209hh-20-inch-planer', 'Stationary Tools', 'cabinet-making', 'used-excellent', 4900.00, 'USD', 'Powermatic 209HH 20" planer with Byrd Shelix helical cutterhead upgraded 2 years ago. Perfect condition, runs quiet, cuts glass-smooth. Single-phase 5 HP.', 'Charlotte, NC', true, false),
  ('Oliver 14" Bandsaw — Restored', 'oliver-14-inch-bandsaw-restored', 'Stationary Tools', 'cabinet-making', 'used-excellent', 2800.00, 'USD', 'Oliver 14" bandsaw, fully restored. New bearings, new tires, re-painted, re-wired single-phase. Runs like a new machine. Includes fence and mitre gauge.', 'Portland, ME', true, false),
  ('SawStop Industrial Cabinet Saw — 5HP 3-Phase', 'sawstop-industrial-cabinet-saw-5hp-3ph', 'Stationary Tools', 'safety-standards', 'used-excellent', 4200.00, 'USD', 'SawStop Industrial 5 HP 3-phase cabinet saw with 52" Biesemeyer fence, 36" rails. Lightly used in a non-production furniture shop. Never triggered.', 'Asheville, NC', true, false),
  ('Festool Domino DF 700 XL with Systainer Set', 'festool-domino-df-700-xl', 'Hand/Power Tools', 'cabinet-making', 'used-excellent', 1250.00, 'USD', 'Festool Domino DF 700 XL with full cutter set, tenon assortment, and Systainer. Used on a single custom stair job, then retired. Like new.', 'Seattle, WA', true, false),
  ('Holz-Her Sprint 1315 CNC Panel Saw', 'holz-her-sprint-1315-panel-saw', 'Panel Saws', 'cnc-machining', 'used-good', 22500.00, 'USD', 'Holz-Her Sprint 1315 vertical panel saw. 8.5 ft cut, diameter 14" blade. Cuts both horizontally and vertically. Runs in our shop daily — removing to free floor space.', 'Chicago, IL', true, false),
  ('Used Shop-Vac Central Dust Collection — 7.5 HP Cyclone', 'shop-dust-collection-75hp-cyclone', 'Dust Collection', 'safety-standards', 'used-good', 3400.00, 'USD', 'Oneida 7.5 HP cyclone with (12) 16 oz cartridge filters, all ducting, blast gates, and manifold. Will sell as-is or installed (installer quote separate).', 'Atlanta, GA', true, false),
  ('Assortment of Hard Maple Lumber — 1200 BF', 'hard-maple-lumber-1200bf', 'Lumber', 'wood-species', 'new', 6800.00, 'USD', 'Kiln-dried hard maple, 4/4 and 5/4 mixed, FAS and Select grades, 8–12 ft lengths. 1,200 BF total. Stickered in a climate-controlled warehouse since 2024.', 'Nashville, TN', true, false),
  ('Quartersawn White Oak Plywood — 1/2" and 3/4"', 'qswo-plywood-half-three-quarter', 'Sheet Goods', 'wood-species', 'new', 4200.00, 'USD', 'Premium quartersawn white oak plywood from Columbia Forest Products, PureBond. 22 sheets of 3/4" and 8 sheets of 1/2". Overrun from a completed kitchen.', 'Louisville, KY', true, false),
  ('Blum Tandem Plus Drawer Slides — Bulk Lot (200 pairs)', 'blum-tandem-plus-drawer-slides-200pair', 'Hardware', 'hardware-accessories', 'new', 7500.00, 'USD', '200 pairs of Blum Tandem Plus Blumotion undermount drawer slides, 563H series, 21" length, 100 lb capacity. Full factory cartons. Priced at roughly 40% off MSRP.', 'Phoenix, AZ', true, false),
  ('Older Brown Enamel Whitney Upright Drill Press', 'whitney-upright-drill-press-enamel', 'Stationary Tools', 'cabinet-making', 'used-fair', 950.00, 'USD', 'Vintage Whitney upright drill press, originally 3-phase converted to single-phase years ago. Table is true, quill travels clean, motor runs. Cosmetic rust only.', 'Cleveland, OH', true, false),
  ('Timesavers 37" 2-Head Widebelt Sander', 'timesavers-37-widebelt-sander', 'Sanders', 'cnc-machining', 'used-good', 18500.00, 'USD', 'Timesavers 37" widebelt sander, combination head (platen + contact drum). 3-phase, 20 HP. New belt included. Ran in our shop on cabinet work — pads available separately.', 'Milwaukee, WI', true, false),
  ('CNC Tooling Bundle — Onsrud Compression & Finishing Bits', 'cnc-tooling-onsrud-bundle', 'Tooling', 'cnc-machining', 'used-good', 1450.00, 'USD', 'Mixed bundle of 34 Onsrud CNC router bits — compression, finishing, downcut, and V-bits. 1/4", 3/8", 1/2" shank. Most have life remaining. Priced well below new.', 'Columbus, OH', true, false),
  ('Kremlin Downdraft Spray Booth — 12x10x9', 'kremlin-downdraft-spray-booth-12x10', 'Finishing', 'finishing-coatings', 'used-good', 9800.00, 'USD', 'Kremlin crossdraft-convertible spray booth, 12x10x9 working envelope, heated make-up air, filter bank. Removed from a closed shop. You transport.', 'Kansas City, MO', true, false),
  ('Lot of Baltic Birch Plywood — 3/4" and 1/2"', 'baltic-birch-plywood-lot', 'Sheet Goods', 'wood-species', 'new', 3900.00, 'USD', 'Genuine Baltic birch plywood — 18 sheets of 3/4" and 14 sheets of 1/2", 5x5 format. Bought for a canceled hospitality project. Fresh from the distributor.', 'Minneapolis, MN', true, false)
on conflict (slug) do update set title = excluded.title, category = excluded.category, trade = excluded.trade, condition = excluded.condition, price = excluded.price, description = excluded.description, location = excluded.location, is_approved = excluded.is_approved, is_sold = excluded.is_sold;

-- ============================================================
-- Summary:
--   Suppliers: 20 total (4 from seed.sql + 16 here)
--   Forum threads: 20
--   Jobs: 20
--   Events: 20
--   Wiki articles: 20
--   News articles: 20
--   Marketplace listings: 20
-- All author_id/seller_id/claimed_by are NULL. After you create your
-- own profile, you can claim content with:
--   update public.suppliers set claimed_by = auth.uid() where slug = '...';
-- ============================================================
